### ISSUE TITLE
Configurable timeout on Guzzle connection

### ISSUE THREAD

**Issue by potibm** [bugsnag/bugsnag-symfony#100]
As we are sometimes experiencing longer response times from our Bugsnag servers it would be great to configure a timeout on the used Guzzle Connection.

Currently this does not seem to be possible.

**Comment by phillipsam** [comment]
Hi @potibm - are you using the on-premise version of Bugsnag?

**Comment by potibm** [comment]
Indeed we are using an on-premise version of Bugsnag. We would like to prevent latency issues with Bugsnag to affect our production perfomance.

**Comment by phillipsam** [comment]
Hi @potibm we would like to understand what latency issues you are having and why you are having them. Can you please write to support@bugsnag.com with some additional information about your use case?

**Comment by potibm** [comment]
As I do not run our Bugsnag servers I think this is beyond this ticket. But I will ask my colleagues to contact your support, of course.

Other than that: latency can happen for whatever reasons (may it be network), so I still would like to set a timeout for the communication with the Bugsnag servers.

**Comment by GrahamCampbell** [comment]
By default, Bugsnag's PHP notifiers don't actually have a connection timeout or a socket timeout when making HTTP requests. It is certainly possible to set a timeout, using the native PHP library (by providing a Guzzle client configured with the timeouts you want), but the current Symfony library doesn't support this, unless you construct the client yourself.

**Comment by yousif-bugsnag** [comment]
Nor released in [v1.8.0](https://github.com/bugsnag/bugsnag-symfony/releases/tag/v1.8.0)
