### ISSUE TITLE
[Bug] auto_notify=false does not work

### ISSUE THREAD

**Issue by FredericGSOI** [bugsnag/bugsnag-symfony#152]
Hello,
It would be useful to desactivate Bugsnag listeners/calls using a config flag.
The "auto_notify" config flag does not work as expected if set to "false" (should avoid all Bugsnag api calls)

**Comment by yousif-bugsnag** [comment]
Hi @FredericGSOI, what API calls you're seeing when that is set to false? The `auto_notify` flag should disable automatic error reporting of unhandled exceptions, but explicit calls to `notifyException` will still result in an API call.

**Comment by johnkiely1** [comment]
Closing this off as we have not heard from you in a while. Happy to re-open and reinvestigate if you can provide the answers to the questions above. Thanks.
