### ISSUE TITLE
Add autoconfigure with symfony flex

### ISSUE THREAD

**Issue by eerison** [bugsnag/bugsnag-symfony#163]
### Add suport for symfony flex
[Symfony Flex](https://symfony.com/doc/current/setup/flex.html) is used to autoconfigure symfony's packages, and it's quite useful when we are setup the lib in our project.

then I was wondering if we could add support for it :)

**Describe the solution you'd like**
Add a default config in https://github.com/symfony/recipes-contrib

**Comment by johnkiely1** [comment]
Hi @eerison, thanks for the suggestion, we've added this to the backlog and will post here as soon as we have updates to share.

**Comment by johnkiely1** [comment]
Hi @eerison, Just wanted to let you know that we have now added a default config recipe for BugSnag with Symfony. https://github.com/symfony/recipes-contrib/tree/main/bugsnag/bugsnag-symfony/1.13
