### ISSUE TITLE
Is it possible to report PHP errors?

### ISSUE THREAD

**Issue by iagomelanias** [bugsnag/bugsnag-symfony#34]
In documentation [there is a section](https://docs.bugsnag.com/platforms/php/symfony/configuration-options/#error-reporting-level) explaining how to configure the error report level. Therefore, when i've created a simple controller with `echo $randomVar` (what would show a undefined variable notice), i haven't received any error in Bugsnag.

I'm using `error_reporting` at the top of my app.php file, just for testing.

My environment is Symfony v3.1.6 and PHP 7.0.12 inside a Linux 14.04 instance.

**Comment by iagomelanias** [comment]
Just updating: some errors, like FatalErrorException are not being sent to Bugsnag too. Basically, what i did was run a specific service with a class as argument. I just put "null" instead the class, when allowing errors to display in the page, i've got the errors normally as text in the page. But they' not being sent to Bugsnag.

**Comment by GrahamCampbell** [comment]
Interesting. Where abouts did you put this code please. Anything that goes through symfony's error handler should get dealt with by Bugsnag.

**Comment by iagomelanias** [comment]
Sorry, it wasn't something related specifically to this bundle.
I was using a custom exception controller for Twig and some errors were not being handled properly, blank pages were being shown instead, exactly as posted [here](https://github.com/symfony/symfony/issues/8703) and [here](https://github.com/symfony/symfony/issues/14669). The errors were not being logged also.

I'm going to close it. Thanks.
