### ISSUE TITLE
Registering callback from service

### ISSUE THREAD

**Issue by TomaszKotlarek** [bugsnag/bugsnag-symfony#35]
Is it possible to register callback, like this for example:
[https://docs.bugsnag.com/platforms/php/symfony/customizing-error-reports/](https://docs.bugsnag.com/platforms/php/symfony/customizing-error-reports/)
...from service container? Like:

    # services.yml
    bugsnag.callbacks.custom_one:
        class: AppBundle\Extensions\Bugsnag\CustomOne
        tags:
            - { name: bugsnag.callback }

How about it?

**Comment by GrahamCampbell** [comment]
No, I don't think it is currently possible.

**Comment by samdjstevens** [comment]
Would you be interested in accepting PRs for this @GrahamCampbell? Was looking for this behaviour myself recently.

**Comment by GrahamCampbell** [comment]
Potentially. Are there any other widely used Symfony packages that do this sort of thing please? I'm just trying to gage what the standard is wrt to Symfony packages.

**Comment by samdjstevens** [comment]
I can't think of any of the top of my head, but some of the Symfony framework standard edition bundles use this kind of "tagged services for extension" pattern. For example, custom Twig filters/functions are registered with the TwigBundle by defining a service and tagging with `twig.extension`.

My actual use case for a feature like this was that I wanted to add some custom data to the BugSnag notifier for every exception, as well as set the user. To achieve this without a way to define a service/callable to be added as a callback, I had to write a high priority listener for `kernel.exception` events, setting the callback last-minute within it, before the exception bubbled to the BugSnag handler listener. 

I think it would be a lot cleaner to define a class/service that implements a `bugSnagCallback(Report)` method (or different - also customisable in tag definition) that once tagged with the appropriate tag gets auto registered by the bundle.

**Comment by samdjstevens** [comment]
@GrahamCampbell any thoughts on this?

**Comment by PReimers** [comment]
@GrahamCampbell @samdjstevens 
Any news on this?

I'm looking for exactly this.

I want to send some additional information and the user (if signed in) with every exception.

**Comment by samdjstevens** [comment]
I'm still happy to submit a PR for this, I think it would be a very lightweight but extremely useful addition to the bundle.

**Comment by GrahamCampbell** [comment]
You guys probably know more about building symfony applications than me, so feel free to submit a PR if you think it's non-controversial. :)

**Comment by samdjstevens** [comment]
Great! Should be able to get one done over the weekend.
