### ISSUE TITLE
Add setReleaseStage to config.yml

### ISSUE THREAD

**Issue by kellymason** [bugsnag/bugsnag-symfony#38]
Allow release stage to be set in `config.yml` in case one wants to override `kernel.environment`.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, The recommended way to set this is programmatically at the moment:

https://docs.bugsnag.com/platforms/php/symfony/configuration-options/#release-stage

**Comment by snmaynard** [comment]
Yeah - we should allow you to override in config.yml unless there is a reason not to?

**Comment by GrahamCampbell** [comment]
Yeh, I agree. I can't remember why this wasn't implemented in both the Laravel and Symfony notifiers. I guess in Laravel it's quite common to perform "configuration" programmatically in service providers.

**Comment by GrahamCampbell** [comment]
I'll have a go at writing this feature in both notifiers, and see if anything jogs my memory as to why it wasn't done before.

**Comment by GrahamCampbell** [comment]
Symfony PR implemented at https://github.com/bugsnag/bugsnag-symfony/pull/39, and Laravel PR implemented at https://github.com/bugsnag/bugsnag-laravel/pull/228.

**Comment by GrahamCampbell** [comment]
The semantics are, if the "release_stage" is set in config, use that, otherwise, fallback to using the application/kernel environment name, as before.

**Comment by GrahamCampbell** [comment]
And for silex: https://github.com/bugsnag/bugsnag-silex/pull/20.
