### ISSUE TITLE
Ignore all 404

### ISSUE THREAD

**Issue by ArnaudTarroux** [bugsnag/bugsnag-symfony#40]
Hi,
I would like to ignore all NotFoundHttpException. Anybody have a solution ? 
Thanks :)

**Comment by GrahamCampbell** [comment]
Yes, you can do this by setting up a filter callback.

https://docs.bugsnag.com/platforms/php/symfony/#custom-diagnostics

To skip sending the report, you can return false from that Closure. You can find all the methods available on the report object at https://github.com/bugsnag/bugsnag-php/blob/master/src/Report.php. Specifically, you will probably be interested in comparing `$report->getName()` with the full exception class name.

**Comment by ArnaudTarroux** [comment]
thanks you @GrahamCampbell :)
