### ISSUE TITLE
Cannot set custom callback for bugsnag

### ISSUE THREAD

**Issue by thentges** [bugsnag/bugsnag-symfony#50]
Hello, 
I installed Bugsnag successfully on my Symfony project. Bugsnag is sending me all the errors.

Now that the configuration is OK, i wanted to add a custom Callback to choose wether i should send the bug to bugsnag or not, but here is my problem :

when i add these lines to my boot() method (in AppKernel)
$bugsnag = $this->getBundle('bugsnag');
$bugsnag->registerCallback(function ($report) { ...});

I get the following error : Bundle "bugsnag" does not exist or it is not enabled, altought i registered the bundle (new Bugsnag\BugsnagBundle\BugsnagBundle(),)..
When i try $this->getBundle('BugsnagBundle') i get an error telling me the "registerCallback" method does not exists for this bundle.

Any idea on how to solve this problem ?

Thanks

**Comment by Cawllec** [comment]
Hi @thentges, I'm having a look into this now and will get back to you as soon as possible.

**Comment by Cawllec** [comment]
I've looked into this and it seems the method our example and documentation are telling your to use are actually incorrect.  Instead of calling:
```php
$bugsnag = $this->getBundle('bugsnag');
```
you need to call:
```php
$bugsnag = $this->getContainer()->get('bugsnag');
```
Try that out and let me know if it helps.  I'll get this patched ASAP.

**Comment by thentges** [comment]
Thanks a lot, this is working now. 
I could have thought of this before.. 

Thanks ;)
