### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by nviitala** [bugsnag/bugsnag-symfony#53]
composer.json should be updated to support also Symfony 4, currently requiring this project is impossible for it.

**Comment by GrahamCampbell** [comment]
I think this is first pending checking everything works properly on Symfony 4, before bumping the version.

**Comment by kattrali** [comment]
Testing and releasing a new version sound like the way forward, thanks @nviitala @GrahamCampbell

**Comment by Cawllec** [comment]
Hi @nviitala, I've created a PR #55 that should fix this, with some instruction in the example of how to get Bugsnag set up with the new Symfony 4 dependency injection methods.  I'll get this merged and released as soon as able.

**Comment by nviitala** [comment]
Awesome, thank you!

**Comment by sebastianwos** [comment]
Hey guys ! When are you planning to release updated version ? Because right now there is no way to require this bundle for symfony 4

**Comment by Cawllec** [comment]
I'm in the process of updating some documentation, and plan to release either today or tomorrow.

**Comment by sebastianwos** [comment]
That's great news :) Thanks !

**Comment by pensiero** [comment]
+1 thank you guys, really up to date! waiting for the release

**Comment by kattrali** [comment]
Resolved in [v1.5.0](https://github.com/bugsnag/bugsnag-symfony/releases/tag/v1.5.0)
