### ISSUE TITLE
Consider not notifying on HttpExceptions

### ISSUE THREAD

**Issue by Richtermeister** [bugsnag/bugsnag-symfony#67]
Hi all, a minor suggestion, with friendly reference to https://github.com/evolution7/Evolution7BugsnagBundle/blob/master/EventListener/Exception/HttpKernelListener.php#L45-L47

### Expected behavior
4** range errors should not trigger error notifications, since these types of Exceptions are handled via Symfony and not logged as error.

### Observed behavior
4** range errors trigger error notifications

### Steps to reproduce
Request a non-existing URL or otherwise trigger a 403/401 error and receive an error notification

### Version
1.5.0

### Additional information
I understand this behavior can be suppressed by registering a custom callback, but out of the box I imagine most people, including Bugsnag operators, would like to suppress a flood of 404 reports, which other solutions are more adept at monitoring.

Thank you for your time.

**Comment by Cawllec** [comment]
Upon reviewing this there's potential to add an `ignoreClasses` configuration option for exception classes, [similar to our Ruby notifier](https://docs.bugsnag.com/platforms/ruby/other/configuration-options/#ignore_classes).  I've raised this as product feedback and will update this thread when able.

**Comment by liweiyi88** [comment]
Or the solution provided by the closed issue works https://github.com/bugsnag/bugsnag-symfony/issues/40.

**Comment by MatTheCat** [comment]
Symfony provides an `excluded_http_codes` configuration for Monolog. It would be good to have something similar.

**Comment by hellojmbtech** [comment]
Can I plus one having a simple bit of YAML config to ignore certain classes of errors? Having to write a custom bit of PHP is a bit over the top. 

If you are going to require custom PHP, could you at least update https://docs.bugsnag.com/platforms/php/symfony/customizing-error-reports/ to have a good example so we can copy and paste?

Also, https://docs.bugsnag.com/platforms/php/symfony/customizing-error-reports/#adding-callbacks is out of date - Symfony 5 does not have an app/AppKernel.php file any more.

**Comment by hellojmbtech** [comment]
And to answer your questions, I want to filter out Symfony\Component\HttpKernel\Exception\NotFoundHttpException and maybe Symfony\Component\HttpKernel\Exception\BadRequestHttpException. When I care about monitoring 404's I'll just look in server logs, but most of the time I don't care as almost all of them are just bots scanning my site for Wordpress hacks.

**Comment by mattdyoung** [comment]
Just to confirm we're currently looking into how best to implement a config option for a list of `discardClasses` across our PHP libraries including Symfony.

We'll keep this issue up to date with the details.

**Comment by phillipsam** [comment]
We have now implemented support the new `discardClasses` configuration option in [v1.9.0](https://github.com/bugsnag/bugsnag-symfony/releases/tag/v1.9.0). Let us know if you have any questions or contact us at support@bugsnag.com!
