### ISSUE TITLE
Broken ClientFactory

### ISSUE THREAD

**Issue by mschaffr** [bugsnag/bugsnag-symfony#7]
Hi there,

after composer installation I got the following error after clearing the cache:

> Compile Error: Cannot use Bugsnag\Configuration as Configuration because the name is already in use

So far I can see, the problem is following use statement
`use Bugsnag\Configuration;`
in [Bugsnag\BugsnagBundle\DependencyInjection\ClientFactory](https://github.com/bugsnag/bugsnag-symfony/blob/master/DependencyInjection/ClientFactory.php#L7)

If there will be an alias, you need also adjust in "make" method, [renaming Configuration with alias](https://github.com/bugsnag/bugsnag-symfony/blob/master/DependencyInjection/ClientFactory.php#L120).
`$client = new Client(new Configuration($this->key), $this->resolver, $guzzle);`

Problem is that Bugsnag\BugsnagBundle\DependencyInjection namespace already contains Configuration class.

After fixing that, a new issue will appear
> Type error: Argument 2 passed to Bugsnag\Client::notifyException() must be callable, array given, called in /home/vagrant/zolar-of
  fer-calculator/vendor/bugsnag/bugsnag-symfony/EventListener/BugsnagListener.php on line 107

I did not take a look at that further yet, but maybe you'll fix that so that I could use this bugsnag repo for my projects in future. :)

Best
Markus

**Comment by GrahamCampbell** [comment]
Thanks for the report. https://github.com/bugsnag/bugsnag-symfony/pull/8 should fix this.

**Comment by GrahamCampbell** [comment]
And #9 should fix the issue with notifying exceptions within the cli.
