### ISSUE TITLE
unit tests fail for bigger project

### ISSUE THREAD

**Issue by hassandaru** [bugsnag/bugsnag-symfony#76]
After installing the package on symfony 2.8.49 and running phpunit test v6.5.8 , bugsnag/bugsnag-symfony: v1.4.0 every instance of phpunit test creates a new instance of bugsnag client which causes memory leaks and tests failing.
test fail message:

Trace:
Warning: include(/Users/project/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/ContextErrorException.php): failed to open stream: Too many open files in /Users/project/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening '/Users/project/vendor/composer/../symfony/symfony/src/Symfony/Component/Debug/Exception/ContextErrorException.php' for inclusion (include_path='.:/usr/local/Cellar/php@7.1/7.1.26/share/php@7.1/pear') in /Users/project/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(/Users/project/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/ContextErrorException.php): failed to open stream: Too many open files in /Users/project/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/Users/project/vendor/composer/../symfony/symfony/src/Symfony/Component/Debug/Exception/ContextErrorException.php' for inclusion (include_path='.:/usr/local/Cellar/php@7.1/7.1.26/share/php@7.1/pear') in /Users/project/vendor/composer/ClassLoader.php on line 444

Fatal error: Method PHPUnit\Framework\ExceptionWrapper::__toString() must not throw an exception, caught ErrorException: Warning: include(/Users/project/vendor/phpunit/phpunit/src/Util/Filter.php): failed to open stream: Too many open files in /Users/project/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php on line 0
PHP Fatal error:  Method PHPUnit\Framework\ExceptionWrapper::__toString() must not throw an exception, caught ErrorException: Warning: include(/Users/project/vendor/phpunit/phpunit/src/Util/Filter.php): failed to open stream: Too many open files in /Users/project/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php on line 0

Fatal error: Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalErrorException' not found in /Users/project/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:705
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler::handleFatalError()
#1 {main}
  thrown in /Users/project/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php on line 705
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalErrorException' not found in /Users/project/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:705

**Comment by snmaynard** [comment]
I recommend contacting support@bugsnag.com with this - they will be able to assist you better. Thanks!
