### ISSUE TITLE
Add support for Symfony 5

### ISSUE THREAD

**Issue by pyrech** [bugsnag/bugsnag-symfony#91]
### Expected behavior
*Compatibility with Symfony 5*

### Observed behavior
*composer.json dependencies prevent Symfony 5 to be installed*

As Symfony 5 is about to be released at the end of the month (currently in beta), did you plan to release a new version of this bundle to add the compatibility soon?
If not, I may find the time to make a PR if you need help :slightly_smiling_face:

**Comment by pyrech** [comment]
I just made the PR to add support for Sf 5 :+1: #92

**Comment by mattdyoung** [comment]
Now released in [v1.6.0](https://github.com/bugsnag/bugsnag-symfony/releases/tag/v1.6.0)
