### ISSUE TITLE
GetResponseForExceptionEvent deprecation notice still occurs in 1.6

### ISSUE THREAD

**Issue by likeuntomurphy** [bugsnag/bugsnag-symfony#97]
### Expected behavior
With the changes in #93, no deprecation notices should be thrown.

### Observed behavior
I am still seeing this notice:

> User Deprecated: The "Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent::getException()" method is deprecated since Symfony 4.4, use "getThrowable()" instead.

### Steps to reproduce
The easiest thing to do is to hit a route behind a firewall to trigger an `AccessDeniedException` in dev and check the deprecation logs in the profiler.

### Version
1.6 (Symfony 4.4)

### Additional information
The conditional checks in `BugsnagListener::onKernelException()` need to be reversed so that `ExceptionEvent` is checked first — because it simply extends `GetResponseForExceptionEvent`, the first condition is also true and hence the deprecation notice is still thrown.

**Comment by mattdyoung** [comment]
Hi @likeuntomurphy 

Thanks for raising this. We're aiming to fix in the next release.

**Comment by tomlongridge** [comment]
This is now fixed in [1.6.1](https://github.com/bugsnag/bugsnag-symfony/releases/tag/v1.6.1).
